export type WeatherBriefScene =
  | 'WET_TRAVEL'
  | 'CAREFUL_STEPS'
  | 'MASK_READY'
  | 'SHADE_BREAK'
  | 'LAYER_READY'
  | 'STEADY_PACE'
  | 'DAILY_RHYTHM';

type TenBriefOptions = readonly [
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
];

export const WEATHER_BRIEF_SLOT_OPTIONS = {
  eventTime: [
    '새벽녘',
    '아침 일찍',
    '출근길',
    '오전 중',
    '점심때',
    '한낮',
    '오후 한때',
    '퇴근길',
    '저녁때',
    '늦은 밤',
  ],
  wetAction: [
    '작은 우산 하나면',
    '접이식 우산을 챙기면',
    '가벼운 우산을 곁에 두면',
    '가방에 우산을 더하면',
    '손에 익은 우산을 챙기면',
    '문 앞의 우산을 확인하면',
    '가방 속 우산을 살펴보면',
    '우산에 작은 자리를 내주면',
    '외출 목록에 우산을 더하면',
    '여분 우산을 가까이 두면',
  ],
  wetBenefit: [
    '돌아오는 길이 든든해져요',
    '예상 밖 순간에도 안심돼요',
    '긴 외출 끝까지 마음이 놓여요',
    '귀갓길에 작은 여유가 생겨요',
    '이동 계획을 이어가기 편해요',
    '서두르지 않고 마칠 수 있어요',
    '작은 준비가 제 몫을 해줘요',
    '집으로 향하는 마음이 편해져요',
    '바깥 일정 끝까지 안심돼요',
    '챙겨둔 보람이 발걸음에 남아요',
  ],
  stepAction: [
    '한 뼘 줄인 보폭이면',
    '발끝을 천천히 디디면',
    '한 걸음씩 천천히 옮기면',
    '손잡이 가까이 움직이면',
    '발밑을 먼저 살펴보면',
    '여유 있는 걸음을 택하면',
    '익숙한 길도 살펴 걸으면',
    '두 손을 가볍게 비우면',
    '급한 마음을 잠시 놓으면',
    '편한 동선을 골라두면',
  ],
  stepBenefit: [
    '발끝까지 마음이 놓여요',
    '목적지까지 차분히 닿아요',
    '익숙한 길도 든든해져요',
    '걸음마다 여유를 지켜줘요',
    '작은 보폭이 균형을 잡아줘요',
    '일정을 차분히 이어갈 수 있어요',
    '돌아오는 길도 편안해져요',
    '바깥 걸음이 안정돼요',
    '한 걸음마다 안심이 생겨요',
    '걸음과 마음이 함께 차분해져요',
  ],
  maskAction: [
    '가벼운 마스크를 챙기면',
    '잘 맞는 마스크를 넣어두면',
    '외출 목록에 마스크를 더하면',
    '여분 마스크를 주머니에 두면',
    '문 앞에서 마스크를 확인하면',
    '편한 마스크를 가까이 두면',
    '마스크 끈을 미리 살펴두면',
    '익숙한 마스크를 챙겨두면',
    '작은 마스크 파우치를 준비하면',
    '마스크 한 장에 자리를 내주면',
  ],
  maskBenefit: [
    '바깥 호흡이 한결 편안해져요',
    '긴 이동에도 여유가 남아요',
    '사람 많은 길에서도 든든해요',
    '외출 내내 숨 고르기가 수월해요',
    '하루 동선을 편하게 이어가요',
    '민감한 순간을 가볍게 넘겨요',
    '문밖의 시간을 차분히 보내요',
    '돌아올 때까지 작은 안심이 돼요',
    '바깥 일정에 든든한 틈이 생겨요',
    '내 호흡을 살필 여유가 생겨요',
  ],
  shadeAction: [
    '그늘이 이어진 길을 고르면',
    '잠깐 쉴 자리를 떠올리면',
    '시원한 물 한 모금을 두면',
    '가벼운 양산을 더하면',
    '쉬어갈 곳을 미리 정하면',
    '걷는 구간을 짧게 나누면',
    '물병을 가까이 준비하면',
    '바깥 일정을 느긋하게 나누면',
    '그늘 쪽 동선을 골라두면',
    '얇은 챙 모자를 곁에 두면',
  ],
  shadeBenefit: [
    '한낮의 발걸음이 가벼워져요',
    '바깥 일정에 쉴 틈이 생겨요',
    '오래 걷는 길도 수월해져요',
    '몸의 리듬을 지키기 편해요',
    '서두르지 않고 하루를 이어가요',
    '이동 사이사이에 여유가 남아요',
    '돌아오는 길까지 기운을 아껴요',
    '짧은 외출도 한결 산뜻해져요',
    '계획한 일정을 부드럽게 마쳐요',
    '몸의 신호를 살피기 쉬워져요',
  ],
  layerAction: [
    '가벼운 겉옷을 한 겹 더하면',
    '얇은 겉옷을 가방에 넣으면',
    '벗어 들기 쉬운 옷을 고르면',
    '목을 감쌀 소품을 챙기면',
    '소매 긴 겉옷을 곁에 두면',
    '얇은 옷을 겹쳐 입으면',
    '옷깃을 여밀 준비를 하면',
    '가방에 여분 한 겹을 더하면',
    '가벼운 옷을 하나 챙기면',
    '벗기 쉬운 옷을 골라두면',
  ],
  layerBenefit: [
    '아침저녁 사이가 편안해져요',
    '바깥 시간이 부드러워져요',
    '옷깃 안쪽에 안심이 생겨요',
    '몸의 리듬을 지키기 쉬워요',
    '하루의 앞뒤가 편하게 이어져요',
    '늦은 귀가에도 든든함이 남아요',
    '실내와 바깥을 오가기 수월해요',
    '긴 외출에도 마음이 놓여요',
    '일정을 그대로 이어가기 편해요',
    '가방 속 한 겹이 힘이 되어줘요',
  ],
  paceAction: [
    '모자와 소지품을 살피면',
    '가벼운 물건을 가방에 넣으면',
    '옷깃과 가방 끈을 여미면',
    '양손을 가볍게 비우면',
    '느긋한 동선을 골라두면',
    '편한 이동 수단을 택하면',
    '소지품을 미리 정리하면',
    '긴 옷자락을 여며두면',
    '보폭을 줄여 움직이면',
    '이동 시간을 넉넉히 두면',
  ],
  paceBenefit: [
    '바깥 걸음이 단정해져요',
    '예상 밖 흔들림에도 안심돼요',
    '몸의 중심을 잡기 쉬워져요',
    '목적지까지 차분히 닿아요',
    '소지품 걱정이 한결 줄어요',
    '바깥 일정이 차분히 이어져요',
    '문밖의 순간이 편안해져요',
    '발걸음마다 여유가 남아요',
    '돌아오는 길도 안정돼요',
    '작은 준비가 균형을 잡아줘요',
  ],
  rhythmAction: [
    '미뤄둔 산책을 꺼내면',
    '짧은 외출을 더해보면',
    '하루의 순서를 정리하면',
    '좋아하는 음악과 나서면',
    '천천히 걷는 시간을 만들면',
    '가까운 약속부터 이어가면',
    '미뤄둔 볼일을 꺼내보면',
    '평소 속도로 하루를 열면',
    '가벼운 계획부터 펼치면',
    '잠깐 바깥 시간을 마련하면',
  ],
  rhythmBenefit: [
    '하루의 리듬이 부드럽게 이어져요',
    '계획한 순서가 자연스럽게 흘러요',
    '남겨둔 일을 차분히 마쳐요',
    '걸음과 생각의 속도가 맞아가요',
    '서두르지 않아도 하루가 채워져요',
    '평소의 페이스를 편하게 지켜요',
    '작은 움직임이 산뜻한 전환이 돼요',
    '오늘의 시간이 가지런히 이어져요',
    '실내외의 리듬이 자연스럽게 맞아요',
    '계획 사이에 가벼운 여백이 남아요',
  ],
} as const satisfies Record<string, TenBriefOptions>;

export type WeatherBriefSlotKey = keyof typeof WEATHER_BRIEF_SLOT_OPTIONS;

export interface WeatherBriefTemplate {
  id: string;
  scene: WeatherBriefScene;
  text: string;
  slots: readonly WeatherBriefSlotKey[];
}

export const WEATHER_BRIEF_TEMPLATES = [
  {
    id: 'wet-travel-01',
    scene: 'WET_TRAVEL',
    text: '오늘 {eventTime}, {wetAction} {wetBenefit}.',
    slots: ['eventTime', 'wetAction', 'wetBenefit'],
  },
  {
    id: 'wet-travel-02',
    scene: 'WET_TRAVEL',
    text: '{eventTime}엔 {wetAction} {wetBenefit}.',
    slots: ['eventTime', 'wetAction', 'wetBenefit'],
  },
  {
    id: 'wet-travel-03',
    scene: 'WET_TRAVEL',
    text: '하루 중 {eventTime}엔 {wetAction} {wetBenefit}.',
    slots: ['eventTime', 'wetAction', 'wetBenefit'],
  },
  {
    id: 'careful-steps-01',
    scene: 'CAREFUL_STEPS',
    text: '오늘 {eventTime}, {stepAction} {stepBenefit}.',
    slots: ['eventTime', 'stepAction', 'stepBenefit'],
  },
  {
    id: 'careful-steps-02',
    scene: 'CAREFUL_STEPS',
    text: '{eventTime}엔 {stepAction} {stepBenefit}.',
    slots: ['eventTime', 'stepAction', 'stepBenefit'],
  },
  {
    id: 'careful-steps-03',
    scene: 'CAREFUL_STEPS',
    text: '하루 중 {eventTime}엔 {stepAction} {stepBenefit}.',
    slots: ['eventTime', 'stepAction', 'stepBenefit'],
  },
  {
    id: 'mask-ready-01',
    scene: 'MASK_READY',
    text: '오늘 {eventTime}, {maskAction} {maskBenefit}.',
    slots: ['eventTime', 'maskAction', 'maskBenefit'],
  },
  {
    id: 'mask-ready-02',
    scene: 'MASK_READY',
    text: '{eventTime}엔 {maskAction} {maskBenefit}.',
    slots: ['eventTime', 'maskAction', 'maskBenefit'],
  },
  {
    id: 'mask-ready-03',
    scene: 'MASK_READY',
    text: '하루 중 {eventTime}엔 {maskAction} {maskBenefit}.',
    slots: ['eventTime', 'maskAction', 'maskBenefit'],
  },
  {
    id: 'shade-break-01',
    scene: 'SHADE_BREAK',
    text: '오늘 {eventTime}, {shadeAction} {shadeBenefit}.',
    slots: ['eventTime', 'shadeAction', 'shadeBenefit'],
  },
  {
    id: 'shade-break-02',
    scene: 'SHADE_BREAK',
    text: '{eventTime}엔 {shadeAction} {shadeBenefit}.',
    slots: ['eventTime', 'shadeAction', 'shadeBenefit'],
  },
  {
    id: 'shade-break-03',
    scene: 'SHADE_BREAK',
    text: '하루 중 {eventTime}엔 {shadeAction} {shadeBenefit}.',
    slots: ['eventTime', 'shadeAction', 'shadeBenefit'],
  },
  {
    id: 'layer-ready-01',
    scene: 'LAYER_READY',
    text: '오늘 {eventTime}, {layerAction} {layerBenefit}.',
    slots: ['eventTime', 'layerAction', 'layerBenefit'],
  },
  {
    id: 'layer-ready-02',
    scene: 'LAYER_READY',
    text: '{eventTime}엔 {layerAction} {layerBenefit}.',
    slots: ['eventTime', 'layerAction', 'layerBenefit'],
  },
  {
    id: 'layer-ready-03',
    scene: 'LAYER_READY',
    text: '하루 중 {eventTime}엔 {layerAction} {layerBenefit}.',
    slots: ['eventTime', 'layerAction', 'layerBenefit'],
  },
  {
    id: 'steady-pace-01',
    scene: 'STEADY_PACE',
    text: '오늘 {eventTime}, {paceAction} {paceBenefit}.',
    slots: ['eventTime', 'paceAction', 'paceBenefit'],
  },
  {
    id: 'steady-pace-02',
    scene: 'STEADY_PACE',
    text: '하루 중 {eventTime}엔 {paceAction} {paceBenefit}.',
    slots: ['eventTime', 'paceAction', 'paceBenefit'],
  },
  {
    id: 'daily-rhythm-01',
    scene: 'DAILY_RHYTHM',
    text: '오늘 {eventTime}, {rhythmAction} {rhythmBenefit}.',
    slots: ['eventTime', 'rhythmAction', 'rhythmBenefit'],
  },
  {
    id: 'daily-rhythm-02',
    scene: 'DAILY_RHYTHM',
    text: '{eventTime}엔 {rhythmAction} {rhythmBenefit}.',
    slots: ['eventTime', 'rhythmAction', 'rhythmBenefit'],
  },
  {
    id: 'daily-rhythm-03',
    scene: 'DAILY_RHYTHM',
    text: '하루 중 {eventTime}엔 {rhythmAction} {rhythmBenefit}.',
    slots: ['eventTime', 'rhythmAction', 'rhythmBenefit'],
  },
] as const satisfies readonly WeatherBriefTemplate[];
