/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings src/worker-configuration.d.ts` (hash: 32b1c4ea8913af85aba67aa072d90bcb)
interface __BaseEnv_CloudflareBindings {
	DB: D1Database;
	APP_ORIGIN: "http://localhost:8787";
	FCM_PROJECT_ID: "weather-care-2aaa8";
	KMA_SERVICE_KEY: string;
	KMA_APIHUB_KEY: string;
	FCM_CLIENT_EMAIL: string;
	FCM_PRIVATE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "FCM_PROJECT_ID" | "KMA_SERVICE_KEY" | "KMA_APIHUB_KEY" | "FCM_CLIENT_EMAIL" | "FCM_PRIVATE_KEY">> {}
}
