name: weather_care
description: "Weather Care - Lifestyle-first weather app scaffold"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  firebase_analytics: ^12.4.6
  firebase_core: ^4.13.0
  flutter:
    sdk: flutter
  google_mobile_ads: ^7.0.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - config/
