name: weather_care
description: "Weather Care - Lifestyle-first weather app scaffold"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  firebase_analytics: ^12.4.6
  firebase_core: ^4.13.0
  flutter:
    sdk: flutter
  google_mobile_ads: ^7.0.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - config/
  fonts:
    - family: SUITE
      fonts:
        - asset: assets/fonts/SUITE-Light.ttf
          weight: 300
        - asset: assets/fonts/SUITE-Regular.ttf
          weight: 400
        - asset: assets/fonts/SUITE-Medium.ttf
          weight: 500
        - asset: assets/fonts/SUITE-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SUITE-Bold.ttf
          weight: 700
        - asset: assets/fonts/SUITE-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SUITE-Heavy.ttf
          weight: 900
    - family: ChosunCentennial
      fonts:
        - asset: assets/fonts/ChosunCentennial.ttf
          weight: 400
    - family: Mona
      fonts:
        - asset: assets/fonts/Mona10.ttf
          weight: 400
        - asset: assets/fonts/Mona10-Bold.ttf
          weight: 700
    - family: NeoHyundai
      fonts:
        - asset: "assets/fonts/NeoHyundai L.ttf"
          weight: 300
        - asset: "assets/fonts/NeoHyundai R.ttf"
          weight: 400
        - asset: "assets/fonts/NeoHyundai B.ttf"
          weight: 700
        - asset: "assets/fonts/NeoHyundai EB.ttf"
          weight: 800
        - asset: "assets/fonts/NeoHyundai EBK.ttf"
          weight: 900
