name = "weather-care-server"
main = "src/index.ts"
compatibility_date = "2026-08-11"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "weather_care_db"
database_id = "9d1c83ca-9626-4b92-b4ea-db7433115324"

[vars]
APP_ORIGIN = "http://localhost:8787"
FCM_PROJECT_ID = "weather-care-2aaa8"

[secrets]
required = ["KMA_SERVICE_KEY", "KMA_APIHUB_KEY", "FCM_CLIENT_EMAIL", "FCM_PRIVATE_KEY"]

[observability]
enabled = true
head_sampling_rate = 1

[triggers]
crons = ["*/10 * * * *"]
