storePassword=weathercare
keyPassword=weathercare
keyAlias=weathercare
storeFile=D:/IdeaProjects/weather_care/weather_care_app/android/weather_care.jks
applicationId=com.codesoha.weathercare
versionCode=26100200
versionName=1.0.0